import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

interface Props {
  data: {
    message: string;
  };
}
const Home = ({ data }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{data && <p>{data.message}</p>}</main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  let data = null;
  let error = null;

  try {
    const response = await fetch("http://localhost:3001/test/");
    if (response.ok) {
      data = await response.json();
    } else {
      error = {
        statusCode: response.status,
        message: response.statusText,
      };
    }
  } catch (e) {
    error = e;
  }

  return {
    props: { data, error },
  };
}
